// Generated from Precios.csv dynamically
const inventory = [
  {
    "id": "0",
    "type": "individual",
    "title": "Introducción a los Tangos",
    "price": "24,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso • Core Nivel 1",
    "desc": "Domina el compás de 12 tiempos y los acentos fundamentales de los Tangos flamencos. Aprende las falsetas tradicionales esenciales y el ritmo de acompañamiento para empezar a sonar con duende.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "1",
    "type": "individual",
    "title": "Introducción a las Alegrías",
    "price": "24,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso • Core Nivel 1",
    "desc": "Aprende el compás alegre y festivo de las Alegrías de Cádiz. Analiza la estructura tradicional, el silencio, la castellana y las falsetas clásicas con todo el aire del mar.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "2",
    "type": "individual",
    "title": "Introducción a la Soleá",
    "price": "24,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso • Core Nivel 1",
    "desc": "Adéntrate en la Soleá, considerada la madre del flamenco. Aprende a controlar el compás lento, la solemnidad del toque y las falsetas básicas para comprender la base de la guitarra.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "3",
    "type": "individual",
    "title": "Introducción a los Fandangos",
    "price": "24,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso • Core Nivel 1",
    "desc": "Explora la belleza melódica y el compás de 3/4 de los Fandangos. Aprende la rueda de acordes clásica, las variaciones de pulgar y la expresividad necesaria para este palo fundamental.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "4",
    "type": "individual",
    "title": "Introducción a las Bulerías",
    "price": "24,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso • Core Nivel 1",
    "desc": "Conquista el latido absoluto del flamenco. Aprende el ciclo esencial de 12 tiempos, rasgueos básicos y falsetas introductorias de alto impacto que le dan a tu guitarra ese auténtico sabor a Jerez.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "5",
    "type": "bundle",
    "title": "5 Palos Clave del Flamenco",
    "price": "89,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Pack Temático • Nivel 1",
    "desc": "El pack introductorio definitivo. Consigue acceso inmediato a los 5 palos clave del flamenco: Tangos, Alegrías, Soleá, Fandangos y Bulerías. Construye tu base rítmica y melódica.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "6",
    "type": "individual",
    "title": "Técnica para Principiantes: Mano Derecha",
    "price": "19,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Técnica • Nivel 1",
    "desc": "Corrige vicios y tensiones desde el primer día. Este módulo de biomecánica se enfoca en la postura de la mano derecha, la colocación del pulgar y la ejecución limpia del picado y rasgueo.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "7",
    "type": "individual",
    "title": "Técnica para Principiantes: Mano Izquierda",
    "price": "19,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Técnica • Nivel 1",
    "desc": "Desarrolla fuerza, agilidad y precisión en la mano izquierda. Ejercicios específicos para mejorar la apertura de los dedos, la claridad de las notas y las transiciones fluidas de acordes.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "8",
    "type": "bundle",
    "title": "Técnica para principiantes: Las dos manos",
    "price": "29,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Pack de Técnica • Nivel 1",
    "desc": "Consigue la sincronización perfecta entre ambas manos. Combina el entrenamiento biomecánico y los ejercicios de coordinación de mano izquierda y derecha para una ejecución limpia.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "9",
    "type": "individual",
    "title": "Cadencia Andaluza",
    "price": "29,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso Especializado • Nivel 1",
    "desc": "Domina el motor armónico del flamenco. Aprende a usar el modo frigio, las sustituciones de acordes, las resoluciones clásicas y los adornos que definen el sonido tradicional andaluz.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "10",
    "type": "individual",
    "title": "Compás y Palmas: El Pulso Flamenco",
    "price": "29,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Curso Especializado • Nivel 1",
    "desc": "Desarrolla un reloj interno inquebrantable. Aprende a marcar el compás, entender los contratiempos y realizar las palmas base y de acompañamiento para los principales palos flamencos.",
    "bundleName": "Deja de ser Payo: El Pack",
    "bundlePrice": "149,99 €",
    "bundleId": "11"
  },
  {
    "id": "11",
    "type": "bundle",
    "title": "Deja de ser Payo: El Pack",
    "price": "149,99 €",
    "level": "Payo",
    "levelSlug": "payo",
    "category": "Pack Completo • Nivel 1",
    "desc": "El plan de estudios básico definitivo. Incluye las introducciones a los 5 palos fundamentales, el sistema completo de técnica para principiantes, Cadencia Andaluza y Compás y Palmas. ¡Ahorra más de 70 €!",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "12",
    "type": "individual",
    "title": "Las Mejores Falsetas por Bulerías",
    "price": "29,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Falsetas • Nivel 2",
    "desc": "Lleva tu toque de Bulerías al siguiente nivel. Aprende falsetas modernas y sincopadas que incorporan contratiempos, patrones rápidos de alzapúa y las melodías de pulgar más populares.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "13",
    "type": "individual",
    "title": "Las Mejores Falsetas por Malagueña",
    "price": "29,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Falsetas • Nivel 2",
    "desc": "Siente el aire de la Malagueña. Aprende falsetas en el estilo clásico de toque libre, centrándote en la expresión dramática, el trémolo y el control del tono y volumen de la guitarra.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "14",
    "type": "individual",
    "title": "Las Mejores Falsetas por Seguiriya",
    "price": "29,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Falsetas • Nivel 2",
    "desc": "El palo más profundo y jondo. Domina la compleja estructura rítmica y las solemnes falsetas de la Seguiriya, combinando la tensión armónica con una gran carga emocional.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "15",
    "type": "individual",
    "title": "Las Mejores Falsetas por Tientos-Tangos",
    "price": "29,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Falsetas • Nivel 2",
    "desc": "Aprende a jugar con el ritmo en la transición de los Tientos (lentos y majestuosos) a los Tangos (rápidos y festivos). Falsetas ideales para dar dinamismo a tu repertorio.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "16",
    "type": "individual",
    "title": "Las Mejores Falsetas por Soleá",
    "price": "29,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Falsetas • Nivel 2",
    "desc": "Profundiza en la Soleá con falsetas de concierto. Aprende a combinar la tradición de la escuela clásica con las armonías modernas de la Soleá contemporánea.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "17",
    "type": "bundle",
    "title": "Falsetero, falsetero",
    "price": "99,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Pack de Falsetas • Nivel 2",
    "desc": "El arsenal definitivo de falsetas intermedias. Consigue las colecciones completas para Bulerías, Malagueña, Seguiriya, Tientos-Tangos y Soleá. Enriquece tu repertorio de concierto al instante.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "18",
    "type": "individual",
    "title": "Técnica para Fenómenos: Mano Derecha",
    "price": "24,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Técnica • Nivel 2",
    "desc": "Supera tus límites de velocidad. Ejercicios avanzados para picado rápido de tres dedos, trémolo flamenco continuo, arpegios complejos y rasgueos de cuatro dedos de alta velocidad.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "19",
    "type": "individual",
    "title": "Técnica para Fenómenos: Mano Izquierda",
    "price": "24,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Técnica • Nivel 2",
    "desc": "Desarrolla la agilidad extrema de la mano izquierda. Prácticas enfocadas en ligados rápidos (pull-offs y hammer-ons), cejillas extendidas, desplazamientos largos y estiramientos avanzados.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "20",
    "type": "bundle",
    "title": "Técnica para Fenómenos: Las Dos Manos",
    "price": "34,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Pack de Técnica • Nivel 2",
    "desc": "Calibración biomecánica para romper barreras. Sincroniza ambas manos para ejecutar pasajes picados a más de 130 BPM con total claridad, relajación y potencia de sonido.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "21",
    "type": "individual",
    "title": "Acompaña al Cante: Teoría y Ejemplos",
    "price": "19,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "El arte de respaldar la voz. Aprende las reglas de oro de la interacción con el cantaor, cómo escuchar las respiraciones, cuándo responder con falsetas y cómo mantener la base.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "22",
    "type": "individual",
    "title": "Acompaña al Cante: Tangos",
    "price": "49,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "Acompañamiento práctico por Tangos. Aprende a marcar el cante, reaccionar a las diferentes letras tradicionales y usar las llamadas y cierres adecuados en cada momento.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "23",
    "type": "individual",
    "title": "Acompaña al Cante: Alegrías",
    "price": "49,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "Domina el acompañamiento en las Alegrías. Aprende la estructura del baile y el cante: la introducción, las letras, la escobilla con el silencio y el dinámico final por Bulerías de Cádiz.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "24",
    "type": "individual",
    "title": "Acompaña al Cante: Bulerías",
    "price": "49,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "El reto máximo de la guitarra de acompañamiento. Aprende a reaccionar en tiempo real a las improvisaciones del cantaor por Bulerías, marcando los acentos y respondiendo con decisión.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "25",
    "type": "individual",
    "title": "Acompaña al Cante: Fandangos Naturales y Personales",
    "price": "49,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "Sigue la libre expresión del cantaor en los Fandangos Naturales. Aprende a guiar armónicamente al cantante sin un compás rígido, respondiendo a su intensidad emocional.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "26",
    "type": "individual",
    "title": "Acompaña al Cante: Fandangos de Huelva y Alosneros",
    "price": "49,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "Acompaña el compás alegre y definido de los Fandangos de Huelva. Domina el ritmo característico de tres tiempos y las falsetas tradicionales de respuesta.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "27",
    "type": "individual",
    "title": "Acompaña al Cante: Cantes de Ida y Vuelta",
    "price": "49,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Acompañamiento al Cante • Nivel 2",
    "desc": "Explora la dulzura de la Guajira, Colombiana y Rumba. Aprende a acompañar estos cantes de influencia latinoamericana, adaptando tu rítmica a sus acentos distintivos.",
    "bundleName": "Soy un Fenómeno: El Pack",
    "bundlePrice": "279,99 €",
    "bundleId": "29"
  },
  {
    "id": "28",
    "type": "bundle",
    "title": "Acompaña al Cante: Más que el Cantaor",
    "price": "199,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Pack de Acompañamiento • Nivel 2",
    "desc": "La biblioteca de acompañamiento al cante más completa del mercado. Consigue la teoría general y los 6 módulos prácticos para convertirte en el apoyo perfecto de cualquier cantaor.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "29",
    "type": "bundle",
    "title": "Soy un Fenómeno: El Pack",
    "price": "279,99 €",
    "level": "Fenómeno",
    "levelSlug": "fenomeno",
    "category": "Pack Completo • Nivel 2",
    "desc": "El pack intermedio definitivo. Todo el repertorio de falsetas de nivel fenómeno, el sistema completo de técnica avanzada y la academia completa de acompañamiento al cante. ¡Conviértete en un Fenómeno!",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "30",
    "type": "individual",
    "title": "Analiza a los Maestros: Paco de Lucía",
    "price": "49,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Análisis de Maestros • Nivel 3",
    "desc": "Estudio exhaustivo del estilo del genio de Algeciras. Analiza los recursos técnicos, las armonías y los conceptos revolucionarios que Paco de Lucía aportó a la guitarra flamenca.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "31",
    "type": "individual",
    "title": "Analiza a los Maestros: Javier Arcos",
    "price": "49,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Análisis de Maestros • Nivel 3",
    "desc": "Accede directamente al lenguaje musical de Javier Arcos. Deconstrucción detallada de sus falsetas de concierto, técnicas predilectas y trucos compositivos.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "32",
    "type": "individual",
    "title": "Analiza a los Maestros: Gerardo Núñez",
    "price": "49,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Análisis de Maestros • Nivel 3",
    "desc": "Explora la velocidad y el lenguaje armónico de Gerardo Núñez. Analiza su increíble picado, sus influencias del jazz y su potente empuje rítmico.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "33",
    "type": "individual",
    "title": "Analiza a los Maestros: Manolo Sanlúcar",
    "price": "49,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Análisis de Maestros • Nivel 3",
    "desc": "Comprende la escuela de Sanlúcar. Deconstrucción de su toque sinfónico, conceptos modales avanzados y el uso de arpegios complejos para pintar paisajes sonoros.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "34",
    "type": "bundle",
    "title": "Analiza a los Maestros: El Maestro eres Tú",
    "price": "149,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Pack de Análisis • Nivel 3",
    "desc": "La enciclopedia del análisis de los grandes maestros. Aprende los secretos compositivos y de ejecución de Paco de Lucía, Javier Arcos, Gerardo Núñez y Manolo Sanlúcar.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "35",
    "type": "individual",
    "title": "Compón tu Primera Pieza",
    "price": "79,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Teoría y Creación • Nivel 3",
    "desc": "Descubre el camino para crear tus propias piezas. Aprende a estructurar una falseta, desarrollar variaciones, conectar diferentes secciones y componer un tema completo y coherente.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "36",
    "type": "individual",
    "title": "Armonía e Improvisación",
    "price": "79,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Teoría y Creación • Nivel 3",
    "desc": "Amplía tu vocabulario musical. Modulaciones complejas, acordes de jazz adaptados a la guitarra flamenca, improvisación sobre el modo frigio y escalas alternativas.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "37",
    "type": "individual",
    "title": "Maestros Invitados: Javier Arcos",
    "price": "99,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Clase Magistral • Nivel 3",
    "desc": "Clase magistral con Javier Arcos enfocada en la preparación profesional. Consejos de grabación en estudio, sonorización en vivo, control del pánico escénico y desarrollo de carrera.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "38",
    "type": "individual",
    "title": "Maestros Invitados: Diego del Morao",
    "price": "99,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Clase Magistral • Nivel 3",
    "desc": "Aprende del rey del swing de Jerez. Diego del Morao explica sus característicos deslizamientos de pulgar, variaciones rítmicas de rasgueo y su filosofía para inyectar un groove inigualable.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "39",
    "type": "individual",
    "title": "Maestros Invitados: Joni Jiménez",
    "price": "99,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Clase Magistral • Nivel 3",
    "desc": "Estudia el elegante estilo de Madrid con Joni Jiménez. Aprende sus falsetas contemporáneas de picado limpio, su uso del pulgar y su forma de entender la Soleá y las Bulerías de hoy.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "40",
    "type": "individual",
    "title": "Maestros Invitados: José del Tomate",
    "price": "99,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Clase Magistral • Nivel 3",
    "desc": "Explora el toque de la dinastía Tomate con José del Tomate. Analiza su velocidad endiablada, sus detalles rítmicos y el legado de su padre Tomatito adaptado al siglo XXI.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "41",
    "type": "individual",
    "title": "Maestros Invitados: Kilino Jiménez",
    "price": "99,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Clase Magistral • Nivel 3",
    "desc": "Clase magistral con Kilino Jiménez. Domina su fusión de velocidad, síncopas perfectas y la precisión rítmica que lo caracteriza en los escenarios más exigentes.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "42",
    "type": "bundle",
    "title": "Maestros Invitados: A tu Casa",
    "price": "199,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Pack de Clases Magistrales • Nivel 3",
    "desc": "El pase definitivo de clases magistrales. Accede a las sesiones exclusivas de Diego del Morao, Joni Jiménez, José del Tomate, Kilino Jiménez y Javier Arcos. Inspiración de élite.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "43",
    "type": "individual",
    "title": "Toca con los Maestros",
    "price": "99,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Práctica Interactiva • Nivel 3",
    "desc": "Práctica real en tu propia casa. Toca sobre pistas de audio interactivas con cante, palmas y percusión real. Ejercicios de llamada y respuesta para ganar seguridad en vivo.",
    "bundleName": "Soy un Maestro: El Pack",
    "bundlePrice": "399,99 €",
    "bundleId": "44"
  },
  {
    "id": "44",
    "type": "bundle",
    "title": "Soy un Maestro: El Pack",
    "price": "399,99 €",
    "level": "Maestro",
    "levelSlug": "maestro",
    "category": "Pack Completo • Nivel 3",
    "desc": "La cima de la educación flamenca. Incluye el curso de Composición, Armonía avanzada, el pack de Análisis de Maestros, las 5 Clases Magistrales y las sesiones de Toca con los Maestros.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  },
  {
    "id": "45",
    "type": "bundle",
    "title": "Descarga completa por nivel",
    "price": "499,99 €",
    "level": "Todos",
    "levelSlug": "todos",
    "category": "Acceso Total • Academia",
    "desc": "El pase definitivo de acceso total. Obtén acceso inmediato e ilimitado a todos los cursos, técnicas, acompañamientos y clases magistrales de los niveles Payo, Fenómeno y Maestro.",
    "bundleName": null,
    "bundlePrice": null,
    "bundleId": null
  }
];
